# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: jar
          path: build/libs/

      - name: Set Lowercase Owner
        run: |
          echo "::set-env name=owner_lowercase::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
        id: set-lowercase-owner

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ steps.set-lowercase-owner.outputs.owner_lowercase }}/keycloak-group-role:$GITHUB_REF_NAME
          docker tag ghcr.io/${{ steps.set-lowercase-owner.outputs.owner_lowercase }}/keycloak-group-role:$GITHUB_REF_NAME ghcr.io/${{ steps.set-lowercase-owner.outputs.owner_lowercase }}/keycloak-group-role:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.set-lowercase-owner.outputs.owner_lowercase }}/keycloak-group-role:$GITHUB_REF_NAME
          docker push ghcr.io/${{ steps.set-lowercase-owner.outputs.owner_lowercase }}/keycloak-group-role:latest
