name: Docker Image CI

on:
  workflow_run:
    workflows: [Java CI with Gradle]
    types:
      - completed
    tags:
     - '*'

jobs:
  on-success:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: jar
          path: build/libs/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/oidc-keycloak-group-role-protocol-mapper/keycloak-group-role:$GITHUB_REF_NAME

      - name: Tag latest
        run: docker tag ghcr.io/oidc-keycloak-group-role-protocol-mapper/keycloak-group-role:$GITHUB_REF_NAME ghcr.io/oidc-keycloak-group-role-protocol-mapper/keycloak-group-role:latest

      - name: Push versioned Docker image
        run: docker push ghcr.io/oidc-keycloak-group-role-protocol-mapper/keycloak-group-role:$GITHUB_REF_NAME

      - name: Push latest Docker image
        run: docker push ghcr.io/oidc-keycloak-group-role-protocol-mapper/keycloak-group-role:latest
